# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgdelta" do
  name "pgdelta"
  desc "Git-native AI-powered PostgreSQL branching tool"
  homepage "https://github.com/ankeshk7/pgdelta"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgdelta"

  on_macos do
    on_intel do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_#{version}_macOS_x86_64.tar.gz"
      sha256 "7b0ed8c120546c1a006ae1b3a57087fa209fb9154b9fc2f8807b3259655649ff"
    end
    on_arm do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_#{version}_macOS_arm64.tar.gz"
      sha256 "2ba250834cacc39fb9db8d1cf6aa1c365c0b59409fb272fcb51010998e44811b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_#{version}_Linux_x86_64.tar.gz"
      sha256 "8b456135b7ace27fbc6dbd70423090f3a20cf067d64232facd16d4f528cbfec9"
    end
    on_arm do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_#{version}_Linux_arm64.tar.gz"
      sha256 "98c134548bf2605fd096ec10f8e92fd5c58afc70bc2b23d21e362f166f209583"
    end
  end

  # No zap stanza required
end
