# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgdelta" do
  name "pgdelta"
  desc "Git-native AI-powered PostgreSQL branching tool"
  homepage "https://github.com/ankeshk7/pgdelta"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgdelta"

  on_macos do
    on_intel do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_#{version}_macOS_x86_64.tar.gz"
      sha256 "223e6865069d4007160c9ac9e58b1f510c909bd258561bf7311cfc8a01bc7c4a"
    end
    on_arm do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_#{version}_macOS_arm64.tar.gz"
      sha256 "429221d6ad0b862646b95388984064985423f49fe7104869f16046786797b1f6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_#{version}_Linux_x86_64.tar.gz"
      sha256 "7782d061ef92321e6ea4d4e3c6873469af86758c94e05143eb781c2e82f4a4bf"
    end
    on_arm do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_#{version}_Linux_arm64.tar.gz"
      sha256 "f842db11a03c12048d3a2bd84d542c8e35bbfb4d3382ee7a098bad41815c1548"
    end
  end

  # No zap stanza required
end
