# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgdelta" do
  name "pgdelta"
  desc "Git-native AI-powered PostgreSQL branching tool"
  homepage "https://github.com/ankeshk7/pgdelta"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgdelta"

  on_macos do
    on_intel do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_Darwin_x86_64.tar.gz"
      sha256 "c4247c9ed3aaa065135151a8463b3dff891afcd608871be11ebcf8d088800b11"
    end
    on_arm do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_Darwin_arm64.tar.gz"
      sha256 "36ff728e64d1dd966bc22af7773d30d93e5f1ab54bb74bbdb8eb96e162183ace"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_Linux_x86_64.tar.gz"
      sha256 "c4cb3d4944fd805938585ce12c6ae2c942697e00f6c0aae06fe4ca1dba805275"
    end
    on_arm do
      url "https://github.com/ankeshk7/pgdelta/releases/download/v#{version}/pgdelta_Linux_arm64.tar.gz"
      sha256 "92a852b73732eab6056b30068cda3a8fd9a701227eda20740c43571aa85c1cec"
    end
  end

  # No zap stanza required
end
